apiVersion: v1
kind: Service
metadata:
  name: genbuilder-service
  labels:
    app: genbuilder
spec:
  type: LoadBalancer
  selector:
    app: genbuilder
    component: api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
